CREATE TABLE Transactions (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    FromWallet BIGINT NOT NULL,
    ToWallet BIGINT NOT NULL,
    TransactionalValue DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(30) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (FromWallet) REFERENCES Wallet(Id),
    FOREIGN KEY (ToWallet) REFERENCES Wallet(Id)
);
