CREATE TABLE Wallet (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Balance DECIMAL(10, 2) NOT NULL,
    UserId CHAR(36) NOT NULL UNIQUE,
    TransactionalPinId BIGINT NOT NULL UNIQUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (UserId) REFERENCES users(Id),
    FOREIGN KEY (TransactionalPinId) REFERENCES TransactionPin(Id)
);
